Repository openshift/operator-curator, pull requests merged in 2019-10, with the labels that each got.

#2 Add some uninstallable operators to the deny list
  curator.py
Labels: lgtm, size/XS

#3 SREP-2215: Summarize results
  .gitignore
  curator.py
Labels: lgtm, size/M

#4 SREP-2230 Safelist CRW operator
  curator.py
Labels: lgtm, size/XS

#5 SREP-2231: look in subdirectories for bundle.yaml file
  curator.py
Labels: lgtm, size/S

#6 Added OWNERS
  OWNERS
Labels: lgtm, size/S

#7 SREP-2206 Truncate and rebuild bundle, to handle prometheus use case
  curator.py
Labels: size/L

#8 SREP-2303 Fix bundle formatting when truncating
  curator.py
Labels: lgtm, size/S

#9 Pylint fixes & others
  .gitignore
  curator.py
Labels: lgtm, size/L
