Repository openshift/operator-curator, pull requests merged in 2019-11, with the labels that each got.

#10 Adding tests and lint fixes, refactor
  Dockerfile
  README.md
  curator.py
  requirements.txt
  test_curator.py
Labels: lgtm, size/XXL

#12 Fix report printing errors
  .gitignore
  curator.py
  test_curator.py
Labels: lgtm, size/M

#11 Added instructions for running curator in docker container
  README.md
Labels: lgtm, size/XS
